databases:
  - name: appapp
    plan: free
    databaseName: appapp
    user: appapp_user

services:
  - type: web
    plan: free
    name: appapp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn appapp.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: appapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 