# Generated by Django 5.0.8 on 2024-08-08 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.ManyToManyField(to='appapp.ingredient')),
                ('rating', models.ManyToManyField(related_name='Rating', to='appapp.rating')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipe', to='appapp.recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='used_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appapp.recipe'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=25)),
                ('ratings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appapp.rating')),
                ('recpies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appapp.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appapp.user'),
        ),
        migrations.AddField(
            model_name='rating',
            name='left_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appapp.user'),
        ),
    ]
