# Generated by Django 5.1 on 2024-08-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapp', '0003_alter_ingredient_used_in_alter_recipe_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appapp.ingredient')),
            ],
        ),
    ]
