# Generated by Django 5.1 on 2024-08-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapp', '0006_remove_recipe_rating_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Rating', to='appapp.rating'),
        ),
    ]
